version: "3"
services: 
  api:
    container_name: api-container
    build: .
    restart: always
    image: elciess-signup
    command: npm start
    volumes: 
      - ./dist:/usr/src/elciess-signup/dist
    ports: 
      - "5050:5050"